name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
#          - macos-latest,
          - ubuntu-latest
#          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies on ${{ matrix.os }}
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt
      - name: Run tests against ${{ matrix.os }}
        run: pytest -v .